### ISSUE TITLE
Add on error on start up - Anki version 23.12.1

### ISSUE THREAD

**Issue by ankiusertiz** [Cardosaum/anki-addons#5]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 219, in on_window_init
  File "_aqt.hooks", line 3553, in __call__
  File "C:\Users\Fekade\AppData\Roaming\Anki2\addons21\1999327581\__init__.py", line 173, in marker_main
    suspend_cards_v2(added_today_only=config_added_today_only)
  File "C:\Users\Fekade\AppData\Roaming\Anki2\addons21\1999327581\__init__.py", line 99, in suspend_cards_v2
    remove_tags(nids_tags_to_remove, " ".join(marker_tags))
  File "C:\Users\Fekade\AppData\Roaming\Anki2\addons21\1999327581\__init__.py", line 68, in remove_tags
    mw.col.tags.bulk_update(nids, tags, "", False)
  File "anki._legacy", line 80, in __getattr__
AttributeError: 'TagManager' object has no attribute 'bulk_update'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Beautify-Anki 20 mizmu ['1116770498', 2023-10-31T14:51, 'None', mod]
Find cards from UWorld test ['444814983', 2023-10-23T05:03, 'None', '']
Hide New Cards Until Next Day ['1999327581', 2022-05-19T14:39, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T00:42, 'None', '']

===IDs of active AnkiWeb add-ons===
1116770498 1374772155 1771074083 1999327581 2040501954 444814983

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by Cardosaum** [comment]
Thanks for the bug report! 

I'll take a look into it. I'd recommend disabling it for now.
